version: '3.8'

services:
    mysql:
        image: mysql/mysql-server:latest
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        tty: true
        ports:
            - '3306:3306'
        env_file:
            - ./mysql/mysql.env
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:apache
        restart: always
        ports:
            - '9083:80'
        links:
            - mysql
        env_file:
            - ./mysql/phpmyadmin.env

volumes:
    db:
